apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: manuela-mcs-gitops-channel-sensores
  namespace: manuela-sensors-mcs
spec:
  type: GitHub
  pathname: https://{{ .Values.global.git.provider }}/{{ .Values.global.git.username }}/blueprints.git


