helm: 
  global:
    git:
      provider: github.com
      account: PLAINTEXT
      username: PLAINTEXT
      email: SOMEWHERE@EXAMPLE.COM
      target: HEAD

    quay:
      provider: quay.io
      account: PLAINTEXT

    datacenter:
      clustername: DATACENTER-CLUSTERNAME
      domain: CLUSTER-DOMAINNAME

    edge:
      clustername: EDGE-CLUSTERNAME
      domain: EDGE-DOMAINNAME

    deploy:
      site: datacenter

  gitops:
    syncPolicy: Automatic

  subscriptions:
    installPlanApproval: Automatic
    version:
      gitops:
        channel: stable   
        csv: v1.2.0
        source: redhat-operators
        syncPolicy: Automatic 
      pipelines:
        channel: stable
        csv: v1.5.0
        source: redhat-operators
      acm:
        channel: release-2.3
        csv: v2.3.1
        source: redhat-operators
      opendatahub:
        channel: stable
        csv: v1.1.0
        source: community-operators
      seldon:
        channel: stable
        csv: v1.7.0
        source: community-operators
      amqbroker:
        channel: 7.x
        csv: amq-broker-operator.v7.8.0
        source: redhat-operators
      amqstreams:
        channel: amq-streams-1.7.x
        csv: v1.7.0
        source: redhat-operators
      redhatcamelk:
        channel: 1.4.x
        csv: v1.4.0
        source: redhat-operators
