apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: factorydatacenter
  namespace: openshift-gitops
  finalizers:
  - argoproj.io/finalizer
spec:
  project: default
  source:
    repoURL: https://{{ .Values.global.git.provider }}/{{ .Values.global.git.username }}/blueprints.git
    targetRevision: HEAD
    path: deployment/staging-factorydatacenter
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status
