# This adds argoCD to all clusters managed by ACM
#
# Probably it needs to only apply to factory clusters
# I remain to be convinced this is the best way to achieve the desired result
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: argocd-sub
  namespace: openshift-gitops
  annotations:
    apps.open-cluster-management.io/github-path: common/argocd
spec:
  channel: argocd-operator-gitops/argocd-operator-channel
  name: argocd-sub
  placement:
    placementRef:
      kind: PlacementRule
      name: apply-argocd-to-ready-clusters
        #apiGroup: apps.open-cluster-management.io
