apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: seldon-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: {{ .Values.subscriptions.version.seldon.channel }}
  installPlanApproval: {{ .Values.subscriptions.installPlanApproval }}
  name: seldon-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
{{- if eq .Values.subscriptions.useCSV "True" }}
  startingCSV: seldon-operator.{{ .Values.subscriptions.version.seldon.csv }}
{{- end }}
