apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
spec:
  channel: {{ .Values.subscriptions.version.pipelines.channel }}
  installPlanApproval: {{ .Values.subscriptions.installPlanApproval }}
  name: openshift-pipelines-operator-rh
  source: {{ .Values.subscriptions.version.pipelines.source }}
  sourceNamespace: openshift-marketplace
  startingCSV: redhat-openshift-pipelines.{{ .Values.subscriptions.version.pipelines.csv }}

