apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: red-hat-camel-k
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: {{ .Values.subscriptions.version.redhatcamelk.channel }}
  installPlanApproval: {{ .Values.subscriptions.installePlanApproval }}
  name: red-hat-camel-k
  source: {{ .Values.subscriptions.version.redhatcamelk.source }}
  sourceNamespace: openshift-marketplace
{{- if eq .Values.subscriptions.useCSV "True" }}
  startingCSV: red-hat-camel-k-operator.{{ .Values.subscriptions.version.redhatcamelk.csv }}
{{- end }}
