apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: anomaly-detection
spec:
  tags:
  - name: 0.3.2-41
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-anomaly-detection:0.3.2-41
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-42
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-anomaly-detection:0.3.2-42
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-43
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-anomaly-detection:0.3.2-43
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-44
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-anomaly-detection:0.3.2-44
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-44
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-anomaly-detection:0.3.2-44
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-51
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-anomaly-detection:0.3.2-51
    importPolicy: {}
    referencePolicy:
      type: Local
