apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: manuela-tst-all
bases: []
images:
- name: messaging
  newName: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/messaging
  newTag: 0.3.2-97
- name: machine-sensor
  newName: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/machine-sensor
  newTag: 0.3.1-55
- name: line-dashboard
  newName: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/line-dashboard
  newTag: 0.3.1-77
- name: anomaly-detection
  newName: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/anomaly-detection
  newTag: 0.3.2-53
