apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams
  namespace: manuela-data-lake-central-kafka-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: {{ .Values.subscriptions.version.amqstreams.channel }}
  installPlanApproval: {{ .Values.subscriptions.installPlanApproval }}
  name: amq-streams
  source: {{ .Values.subscriptions.version.amqstreams.source }}
  sourceNamespace: openshift-marketplace
  startingCSV: amqstreams.{{ .Values.subscriptions.version.amqstreams.csv }}

