apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "manuela-{{ .Values.global.deploy.site }}"
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: manuela
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    repoURL: https://{{ .Values.global.git.provider }}/{{ .Values.global.git.account }}/blueprints.git
    path: manufacturing-edge-ai-ml/{{ .Values.global.deploy.site }}/main
    targetRevision: {{ .Values.global.git.target }}
    helm:
      releaseName: manuela-release-v1
      parameters:
      - name: subscriptions.installPlanApproval
        value: "{{ .Values.subscriptions.installPlanApproval }}"
      - name: subscriptions.useCSV
        value: "{{ .Values.subscriptions.useCSV }}"
        forceString: true
      - name: subscriptions.version.gitops.channel
        value: "{{ .Values.subscriptions.version.gitops.channel }}"
      - name: subscriptions.version.gitops.csv
        value: "{{ .Values.subscriptions.version.gitops.csv }}"
      - name: subscriptions.version.gitops.source
        value: "{{ .Values.subscriptions.version.gitops.source }}"
      - name: subscriptions.version.pipelines.channel
        value: "{{ .Values.subscriptions.version.pipelines.channel }}"
      - name: subscriptions.version.pipelines.csv
        value: "{{ .Values.subscriptions.version.pipelines.csv }}"
      - name: subscriptions.version.pipelines.source
        value: "{{ .Values.subscriptions.version.pipelines.source }}"
      - name: subscriptions.version.acm.channel
        value: "{{ .Values.subscriptions.version.acm.channel }}"
      - name: subscriptions.version.acm.csv
        value: "{{ .Values.subscriptions.version.acm.csv }}"
      - name: subscriptions.version.acm.source
        value: "{{ .Values.subscriptions.version.acm.source }}"
      - name: subscriptions.version.opendatahub.channel
        value: "{{ .Values.subscriptions.version.opendatahub.channel }}"
      - name: subscriptions.version.opendatahub.csv
        value: "{{ .Values.subscriptions.version.opendatahub.csv }}"
      - name: subscriptions.version.opendatahub.source
        value: "{{ .Values.subscriptions.version.opendatahub.source }}"
      - name: subscriptions.version.seldon.channel
        value: "{{ .Values.subscriptions.version.seldon.channel }}"
      - name: subscriptions.version.seldon.csv
        value: "{{ .Values.subscriptions.version.seldon.csv }}"
      - name: subscriptions.version.seldon.source
        value: "{{ .Values.subscriptions.version.seldon.source }}"
      - name: subscriptions.version.amqbroker.channel
        value: "{{ .Values.subscriptions.version.amqbroker.channel }}"
      - name: subscriptions.version.amqbroker.csv
        value: "{{ .Values.subscriptions.version.amqbroker.csv }}"
      - name: subscriptions.version.amqbroker.source
        value: "{{ .Values.subscriptions.version.amqbroker.source }}"
      - name: subscriptions.version.amqstreams.channel
        value: "{{ .Values.subscriptions.version.amqstreams.channel }}"
      - name: subscriptions.version.amqstreams.csv
        value: "{{ .Values.subscriptions.version.amqstreams.csv }}"
      - name: subscriptions.version.amqstreams.source
        value: "{{ .Values.subscriptions.version.amqstreams.source }}"
      - name: subscriptions.version.redhatcamelk.channel
        value: "{{ .Values.subscriptions.version.redhatcamelk.channel }}"
      - name: subscriptions.version.redhatcamelk.csv
        value: "{{ .Values.subscriptions.version.redhatcamelk.csv }}"
      - name: subscriptions.version.redhatcamelk.source
        value: "{{ .Values.subscriptions.version.redhatcamelk.source }}"
      - name: global.quay.provider
        value: "{{ .Values.global.quay.provider }}"
      - name: global.quay.account
        value: "{{ .Values.global.quay.account }}"
      - name: global.git.provider
        value: "{{ .Values.global.git.provider }}"
      - name: global.git.account
        value: "{{ .Values.global.git.account }}"
      - name: global.git.target
        value: "{{ .Values.global.git.target }}"
      - name: global.git.email
        value: "{{ .Values.global.git.email }}"
      - name: global.git.username
        value: "{{ .Values.global.git.username }}"
      - name: global.datacenter.domain
        value: "{{ .Values.global.datacenter.domain }}"
      - name: global.datacenter.clustername
        value: "{{ .Values.global.datacenter.clustername }}"
      - name: global.edge.clustername
        value: "{{ .Values.global.edge.clustername }}"
      - name: global.edge.domain
        value: "{{ .Values.global.edge.domain }}"
      - name: global.deploy.site
        value: "{{ .Values.global.deploy.site }}"
      - name: subscriptions.version.gitops.syncPolicy
        value: "{{ .Values.subscriptions.version.gitops.syncPolicy }}"
{{- if eq .Values.subscriptions.version.gitops.syncPolicy "Automatic" }}
  syncPolicy:
    automated: 
      prune: false
      selfHeal: false
{{- end }}
