apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
  labels:
    operators.coreos.com/openshift-gitops-operator.openshift-operators: ""
spec:
  channel: {{ .Values.subscriptions.version.gitops.channel }}
  installPlanApproval: {{ .Values.subscriptions.installPlanApproval }}
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- if eq .Values.subscriptions.useCSV "True" }}
  startingCSV: openshift-gitops-operator.{{ .Values.subscriptions.version.gitops.csv }}
{{- end }}


  
