apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: machine-sensor
spec:
  tags:
  - name: 0.3.1-37
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-software-sensor:0.3.1-37
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-38
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-software-sensor:0.3.1-38
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-39
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-software-sensor:0.3.1-39
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-40
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-software-sensor:0.3.1-40
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-41
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-41
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-42
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-42
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-42
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-42
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-48
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-software-sensor:0.3.1-48
    importPolicy: {}
    referencePolicy:
      type: Local
