apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: seldon-operator
  namespace: manuela-ml-workspace
spec:
  channel: {{ .Values.subscriptions.version.seldon.channel }}
  installPlanApproval: {{ .Values.subscriptions.installPlanApproval }}
  name: seldon-operator
  source: {{ .Values.subscriptions.version.seldon.source }}
  sourceNamespace: openshift-marketplace
  startingCSV: seldon-operator.{{ .Values.subscriptions.version.seldon.csv }}
